Rakefile, docker-api.gemspec, lib/docker/image.rb, spec/docker/image_spec.rb, spec/vcr/Docker_Image/_create/with_a_block_capturing_create_output/calls_the_block_and_passes_build_output.yml
Captures output from the `/images/create` call and makes it available to an optional block.
In addition, this PR surfaces errors thrown during local registry initialization in the `vcr:spec` rake task.
Great job here, I especially like your clean use of `let`, `subject`, and `context`.
=> Image create captures output

lib/docker/util.rb
Finishes #240 by fixing the ABC complexity error
@bfulton @nahiluhmot @jschneiderhan @myers
This seemed to work appropriately when I tried it locally. I would expect the small script I wrote (attached) to hang since the write end would never be closed, but it ends and prints the output from `cat`.
```
require 'docker'
Docker.options[:ssl_verify_peer] = false
image = Docker::Image.create('fromImage' => 'ubuntu:14.04')
container = Docker::Container.create('Image' => 'ubuntu', 'Cmd' => ['cat'], 'OpenStdin' => true, 'StdinOnce' => true)
puts container.tap(&:start).attach(stdin: StringIO.new("foo\nbar\n"))
```
=> Calling `close_write` on io if necessary

lib/docker/connection.rb, lib/docker/error.rb
This is the simplest form of the fix. It will however break any code that is trying to catch `ConfictError` still. I'm not sure if that is concern, and if it is what the best approach for backward compat might be.
=> fixes #260

README.md
=> Add a section explaining SSL setup

.cane, lib/docker.rb, spec/docker_spec.rb
This allows the user to set ssl_verify_peer to false.
This can be required when running with a self signed cert
=> Option to disable ssl_verify_peer

lib/docker/util.rb, spec/docker/image_spec.rb, spec/support/vcr.rb, spec/vcr/Docker_Image/_build_from_dir/with_a_valid_Dockerfile/with_a_block_capturing_build_output/uses_a_cached_version_the_second_time/calls_the_block_and_passes_build_output.yml
@bfulton @nahiluhmot 
Will fix #269
Pulls in the rubygems code that builds each file in the tar.
=> Verify cache support works

lib/docker/container.rb
By default, docker-api only does retries (`idempotent: true`) for GET requests.  This change is to enable retries for `Container#wait` which, while  technically idempotent without changing server state, uses POST in the API.
=> Enable retries for Container#wait

lib/docker/util.rb
In `Docker::Util#extract_id`. 
Don't know why there was a call to `to_a`, but `lines` always returns an Array.
=> Use reverse_each instead of reverse.each

lib/docker/base.rb
Currently the initializer comment claims that the ID can be optional, but explodes if not present - this corrects the intent in the comment.
=> Correct comment intent

lib/docker/container.rb
Parameter is "user" with the value equal to the in-container username.
Example:
> docker_obj = Docker::Container.get("mycontainer")
> cmd = { "/bin/sh", "ls", "/" }
> opts = { :user => "nobody" }
> docker_obj.exec(cmd,opts)
The Docker engine will use the default value for user if the parameter provided is an empty string, so this should be safe. Tested against Docker 1.7.1 (boot2docker).
=> add user option to list passed along to exec call

README.md
When read the usage, I do find it is hard to get quick understanding to mapping the ruby gem with real docker commands. 
Add comments in README for a quick start. If you like this way, I will add the rest. 
Second, when do the sample to pull image, the command use a fake image named `base`, change it to a real and tiny one, developer can quickly understand how to use it properly
=> Add reference mapping to docker commands - #305

lib/docker/container.rb
Setting `idempotent: true` on the wait request allows excon to retry it. By default, excon seems to retry idempotent failed requests 4 times, and this number can be controlled by the `:retry_limit` option. This means the actual time `Container#wait` waits before giving up is 4 * the given time, on a system without custom Excon options.
VCR asserts don't seem to include idempotency or timeouts, so there are no changes to the test suite. However, I did test this patch on a live system. The retries can be observed by setting the `EXCON_DEBUG=1` environment variable and running `docker-api`-based tests.
Please please please consider merging this or a similar fix. I spent quite a bit of time tracing the root of the timeout issue.
Also, as always, many thanks for this wonderful gem! :heart:
=> Make Container#wait respect the given timeout.

README.md
It took a second to figure out how to stream the logs on our builds, finally we stepped into our context and inspected the methods to find out that builds accepted a block and passed the returned data so we would like that noted so other people can quickly find it without trouble.
=> Show people how to stream the build logs.

README.md, lib/docker-api.rb
With this small addition, users no longer need `require 'docker'` in their Gemfile.
=> Simplify Bundler usage with docker-api

README.md
The documentation implies that you can send a plain string but this
is not true, as Docker will flip out and go crazy when that happens so the
solution here is to send an Array.
=> Update all Docker::Container#exec examples  to use an Array.

lib/docker/image.rb
Check for a fromImage option as both string and symbols, this way
> create('fromImage' => 'foo')
behaves again like
> create(fromImage: 'foo')
to restore compatibility with pre-1.24 behavior.
=> fix regression with symbolized fromImage option on Image#create

README.md
The links to the docker api docs are broken. This fixes them.
=> Fix links to docker api docs

.travis.yml, lib/docker.rb, lib/docker/network.rb, spec/docker/network_spec.rb
This will add the basic `docker network` commands. It will make it possible to create, delete, connect, disconnect and list docker networks.
There are no tests. I ran the test suite and there are so many tests not working with docker 1.9. I started fixing all the tests but then I will break the tests on older versions of docker.
=> Add network command

lib/docker/network.rb
Docker::Network.create now passes the 'conn' parameter to the subsequent 'get' method.
=> Docker::Network.create now passes the 'conn' parameter further.

lib/docker/image.rb
This should fix Image.create on Docker 1.10.x
=> 1.10.x Images - always return imageid fromImage instead of searching response body

lib/docker.rb, spec/docker_spec.rb
Add the possibility to monitor the health of the docker daemon using the ping endpoint of the docker api.
=> Add possibility to call GET /_ping endpoint using Docker.ping

README.md
Added et rewrote example related to #361.
As I wrote the examples, I noticed that there was already an example as the last line of the Containers section but unfortunately I missed it during my troubleshooting. I tried to make it more explicit for newcomers by creating a new section related to JSON encoded values.
=> Add json encoded values example

README.md, lib/docker/image.rb, spec/docker/image_spec.rb
@tlunter Add Docker::Image.save_stream
This method allows the payload one or more Docker images to be streamed into a block.
Docker::Image.save_stream is now used to implement Docker::Image.save to keep the class DRY.
=> Add image save stream

README.md, lib/docker/image.rb, spec/docker/image_spec.rb
@tlunter 
Allow `Docker::Image.load` to accept an `IO` object.
=> Allow image load to accept an io

.travis.yml, lib/docker/util.rb
Image building is broken on (at least) 1.11.1
This patch matches the new output in extract_id
=> Matching new regex in extract_id for image builds

README.md, lib/docker/container.rb, spec/docker/container_spec.rb
This one is really simple, and implements the non-streaming stats endpoint with a basic spec.
I toyed around with adding the streaming stats as well, but found them to be rather pointless b/c you have no control of the interval, whereas this may prove more beneficial (in pseudo i-didn't-feel-like-writing-and-testing-a-real-example code):
```ruby
require 'docker-api'
require 'my-nonexistent-influxdb-library'
influxdb = Influxdb.connect(...)
while true
begin
stats = Docker::Container.get('my-container').stats
influxdb.lineprotocol_write("docker.container_stats,name=my-container cpu_total=#{stats["cpu_stats"]["cpu_usage"]["total_usage"]} #{Influxdb::Util.convert_ts_to_ns(stats["read"])}")
sleep 5
rescue
...
end
end
```
=> Add container stats

lib/docker/container.rb
info has the detailed container information, rather than the more
abbreviated version from other.
Fixes #416
=> Use value from info hash when there is a clash in key.

lib/docker/event.rb, spec/docker/event_spec.rb
This PR pulls in support for the action/actor based fields in the docker events api.  The format for the events api can be found at https://github.com/docker/engine-api/blob/master/types/events/events.go.  I kept support for the older format so this shouldn’t be a breaking change.
=> Support new fields in docker event api

lib/docker/container.rb
add the `:wait` parameter when call `exec.start!`
=> add the :wait parameter to container.exec

lib/docker/image.rb, spec/docker/image_spec.rb
Add the remove method on the class level to avoid instanciation unnecessary calls if you just want to be certain that an image has been removed from your docker host (no need to do exists? or get().remove).
=> Add remove on image class

docker-api.gemspec
- slows down download
- adds weight to external repos when they use vendor/cache
@tlunter
=> do not ship extra files in the gem

lib/docker/connection.rb, lib/docker/container.rb, lib/docker/network.rb, spec/docker/container_spec.rb
Previously if a very long timeout was specified for a container, the HTTP request would likely time out before Docker responded. This ensures that the Docker timeout is hit before the HTTP request timeout configured in Excon
=> Ensure stop & restart timeouts apply to Excon timeout

lib/docker/volume.rb
At current, there's no way to pass any options during the creation of a docker volume. This pull requests fixes it.
=> Adding missing opts parameter to Docker::Volume.create

.gitignore, docker-api.gemspec, lib/docker/event.rb, spec/cov_spec.rb, spec/docker/connection_spec.rb, spec/docker/container_spec.rb, spec/docker/event_spec.rb, spec/docker/exec_spec.rb, spec/docker/image_spec.rb, spec/docker/messages_spec.rb, spec/docker/messages_stack.rb, spec/docker/network_spec.rb, spec/docker/util_spec.rb, spec/docker/volume_spec.rb, spec/docker_spec.rb, spec/spec_helper.rb
@tlunter 
before: useless noise and extra build time
```
Coverage report generated for RSpec to /Users/mgrosser/Code/tools/docker-api/coverage. 283 / 804 LOC (35.2%) covered.
-> 1.0s
```
after: clear info and no runtime overhead
```
lib/docker/util.rb new uncovered lines introduced (86 current vs 85 configured)
Lines missing coverage:
lib/docker/util.rb:15
-> 0.7s
```
I'll add this to all files if you want ... just a taste for now ...
=> use actionable code coverage

docker-api.gemspec
Rather than forcing the ruby version to be 2+, let's just stop testing against 1.9
=> Remove required_ruby_version

lib/docker.rb, lib/docker/connection.rb
**CONTEXT**
When using docker via docker swarm, some commands will no longer return the expected 20X http status code, but instead give a 301 redirect, that the client is expected to follow.
The current version of docker-api (1.32.1), will not follow any redirects, and will raise an exception.
**THIS PR**
This PR will make docker-api automatically follow any HTTP redirects using the excon middleware RedirectFollower.
**TO REPRODUCE THE PROBLEM**
Setup a docker swarm. Then create a connection to it using the Docker class. Attempt to issue an request to a specific container, #kill
**TESTS**
I did not add tests for this PR, because you do not appear to be testing the connection class, beyond ensuring it conforms to Excon compliant output.
=> Follow any redirects to enable swarm support

lib/docker/util.rb
When building an image, if it requires to download parent images and then the build fails, the error is ignored and it returns an invalid image id.
- `docker-api` gem from versions `1.29.0` to `1.33.2` (both included).
A failing *Dockerfile* example:
```Dockerfile
FROM alpine
RUN apk add --update wrong-package-name
```
A small ruby example to build it:
```ruby
require 'docker'
image = Docker::Image.build_from_dir('.') { |v| puts v }
puts "BUILT IMAGE ID: #{image.id}"
```
Shell output:
```
$ docker --version
Docker version 1.11.1, build 5604cbe
$ docker rmi -f alpine:latest
$ ruby docker_ignore_build_error.rb 
{"stream":"Step 1 : FROM alpine\n"}
{"status":"Pulling from library/alpine","id":"latest"}
{"status":"Pulling fs layer","progressDetail":{},"id":"627beaf3eaaf"} …
```
=> Fix ignored build errors when downloading images

lib/docker/util.rb, spec/docker/util_spec.rb
Docker expects the X-Registry-Auth and X-Registry-Config headers to be
encoded using URL-safe Base 64 encoding (the latter is documented,
although the former isn't: https://github.com/moby/moby/issues/33434).
If an incorrect encoding is used, Docker will silently ignore the header
for pulls, and it may fail in other cases.
=> Use correct Base 64 encoding for auth headers

lib/docker/image.rb, spec/docker/image_spec.rb
When a `tag` argument is passed to `Image.create`, that argument needs
to be re-used when loading the image after it's pulled, otherwise trying
to get the image will either crash with a not found error, or return the
wrong image (depending on whether the `latest` tag exists locally for
the repository being pulled).
That part is pretty straightforward, but there are some edge cases when
the user is providing a tag with `fromImage` *and* `tag`.
It is probably desirable to throw an error in most cases: if the user is
confused and passing two different tags, `docker-api` probably shouldn't
venture a guess as to which one they *really* meant (although Docker
itself does assume they meant the one from `tag`). Here, this will fail
by trying to look for an image like `busybox:uclibc:glibc`, which …
=> `Image.create`: support the `tag` argument

lib/docker/image.rb
Fix #489
Note:
I guess it is little confusing. `.create` signature is `create(opts, creds, conn)`, but `.search` signature is `search(query, conn, creds)`. `creds` and `conn` are reversed between them. But it will be a breaking change if it is sorted. WDYT?
=> Make `Docker::Image.search` aware of credentials to search private repositories

lib/docker/container.rb
The `container#create` method mutates the options you provide it which is not good. User passing in configuration objects will find them coming back mutated.
At first I just `.dup`'d the opts, but then a colleague pointed out that `.dup` is shallow. One way to ensure this doesn't happen elsewhere is to `.freeze` the options provided to these methods in the spec suite? That's how I found this bug in the first place.
This method in general seems a little clumsy, maybe other folks can suggest a more full refactor.
=> [BUG] Don't mutate opts on container.create

lib/docker/container.rb
Explanation:
When streaming logs of a container with any size of tail, if there is no log for a while (until the Timeout duration), excon is trying again the request as it is said as idempotent here:
https://github.com/swipely/docker-api/blob/c1387816b6a9d88fe0e26a81af0f4bb3533a18a2/lib/docker/connection.rb#L89
However the tail which has already been sent through the argument block is.. sent again, resulting in having multiple times all the logs coming through the block.
As a result the following code doesn't work (its goal is to restart the streaming after a timeout, without getting existing logs)
```ruby
tail = "all"
begin
container.streaming_logs(follow: true, stderr: true, stdout: true, tail: tail) do |stream, chunk|
puts chunk
end
rescue ::Docker::Error::TimeoutError
tail = 0
retry …
```
=> Disable idempotency when streaming logs, as the operation is not idempotent for the gem consumer

.travis.yml, lib/docker/connection.rb, lib/docker/event.rb, spec/docker/connection_spec.rb, spec/docker/container_spec.rb, spec/docker/event_spec.rb, spec/docker/image_spec.rb, spec/docker_spec.rb, spec/spec_helper.rb
Holding this back to this version limits us whenever new versions of docker come out. Removing this will give us different responses between versions of docker, but we've seen that even when not changing the API version.
Perhaps this is best merged into a 2.0 pre-release with what ever cleanup we want to add versus adding to 1.0.
Thoughts?
=> Remove API version from request path

lib/docker/container.rb
Other options to the `streaming_logs` method read options as strings or symbols. This patch makes the `stack_size` option behave the same way.
=> Accept stack size as string or symbol

.travis.yml, README.md, lib/docker.rb, lib/docker/connection.rb, lib/docker/container.rb, lib/docker/event.rb, lib/docker/image.rb, lib/docker/network.rb, lib/docker/util.rb, lib/docker/version.rb, script/install_docker.sh, spec/docker/connection_spec.rb, spec/docker/container_spec.rb, spec/docker/event_spec.rb, spec/docker/image_spec.rb, spec/docker/messages_spec.rb, spec/docker/network_spec.rb, spec/docker_spec.rb, spec/spec_helper.rb
* Updates Travis CI config to test modern docker engines and ruby versions
* Also fixes broken testing configuration
* Removes version from path (fixes some broken API behavior)
* Fixes deprecation warnings from `URI.encode`
* Remove very legacy `Container#copy` (replaced by `Container#archive_out` in Docker v1.12)
=> Version 2 pre-release

README.md
In the version 2 upgrade, we removed the method in https://github.com/swipely/docker-api/pull/558/commits/f977568213354b4e8c347eeede1346d53aeec723 and its only usage in https://github.com/swipely/docker-api/commit/267f87f1970726513aa237204ce87fe10358dcbf. Cleaning up the reference in README so we can close https://github.com/swipely/docker-api/issues/561 too.
=> Remove reference to `.validate_version!` from README

.cane, .github/workflows/unit_test.yml, README.md, Rakefile, lib/docker.rb, lib/docker/connection.rb, lib/docker/exec.rb, lib/docker/image.rb, script/install_docker.sh, script/install_podman.sh, spec/docker/connection_spec.rb, spec/docker/container_spec.rb, spec/docker/event_spec.rb, spec/docker/exec_spec.rb, spec/docker/image_spec.rb, spec/docker/network_spec.rb, spec/docker_spec.rb, spec/fixtures/build_from_dir/Dockerfile, spec/fixtures/top/Dockerfile
The podman socket will return a note about the correct content-type that
should be used for a given type of message if it is incorrect.
This is a workaround to automatically correct the content-type and
resubmit the call.
A full correction would be to update all of the different connection
entries but this appears to work correctly in the short term.
Fixes #568
=> Automatically retry with correct content-type

.github/workflows/unit_test.yml, Rakefile, docker-api.gemspec, lib/excon/middlewares/hijack.rb, script/install_podman.sh, spec/docker/container_spec.rb, spec/docker/image_spec.rb
__Problem__
As noted in #586, newer versions of Excon will freeze the valid request keys array. At require time, this will raise an error.
__Solution__
In version v0.63/v0.64, there was introduced a method on the base middleware that we can extend to satisfy the requirement necessary for the hijack middleware.
We can bump the minimum required `excon` version, and make use of that method, no longer modifying the constant.
=> Fix #586: require newer excon, use valid parameter keys interface

README.md
This is a small edit to reference `#archive_out` instead of the deprecated and removed `#copy` method in the README.
=> fix: Change reference of #copy to #archive_out
