upserve/docker-api

- lib/docker/container.rb
- spec/docker/container_spec.rb
- spec/vcr/Docker_Container/_rename/renames_the_container.yml
Add method from last API version : https://docs.docker.com/reference/api/docker_remote_api_v1.17/#rename-a-container
> Add rename method for Container

- .cane
- lib/docker/connection.rb
@wyaeld
This will cause the error's message to contain the message from docker. This is what you are expecting?
> The response body contains more helpful information than the message

- lib/docker/connection.rb
> Timeout doesn't have response

- .travis.yml
- lib/docker/container.rb
- lib/docker/messages.rb
- lib/docker/util.rb
- spec/docker/container_spec.rb
- spec/vcr/Docker_Container/_streaming_logs/when_not_selecting_any_stream/raises_a_client_error.yml
- spec/vcr/Docker_Container/_streaming_logs/when_passing_a_block/returns_hello_.yml
- spec/vcr/Docker_Container/_streaming_logs/when_using_a_tty/returns_hello_.yml
@nahiluhmot 
Streaming logs does not return anything when used with a TTY.
> Fix streaming logs for tty

- lib/docker/container.rb
> Docker::Container#exec passing self.connection to Docker::Exec.create

- README.md
Add reference mapping to docker commands in comments
> Add reference mapping to docker commands - #305 - stage 2

- .gitignore
- lib/docker/container.rb
> Add #refresh! to container, mirrors the Image implementation.

- .travis.yml
- Rakefile
- script/install_dependencies.sh
- spec/docker/container_spec.rb
Test against multiple versions of docker
> Perform build matrix on new travis infrastructure

- lib/docker/util.rb
- spec/docker/util_spec.rb
Pertains to #347
@nahiluhmot /cc @rafarost
> Fix X-Registry-Config

- lib/docker.rb
- lib/docker/base.rb
- lib/docker/volume.rb
- spec/docker/volume_spec.rb
> Add volume support

- lib/docker/util.rb
> Handle reading in binary files

- lib/docker/util.rb
- spec/docker/util_spec.rb
> trying to preserve file permissions from host when using insert_local

- README.md
- lib/docker/container.rb
- spec/docker/container_spec.rb
> Added convenience methods for reading and storing files: read_file and store_file

- README.md
- lib/docker/container.rb
- spec/docker/container_spec.rb
- spec/spec_helper.rb
Fixes #387 by not re-specifying headers
> Add support for the update API command

- lib/docker/container.rb
- lib/docker/image.rb
- spec/docker/image_spec.rb
> Docker::Image.run method should support passing additional options as a Hash

- .travis.yml
- docker-api.gemspec
- script/install_docker.sh
- spec/docker/image_spec.rb
- spec/docker_spec.rb
- spec/spec_helper.rb
> drop 1.9 it is dead

- spec/docker/container_spec.rb
> silence warning / impove test

- Rakefile
- spec/spec_helper.rb
@tlunter 
avoids strange errors when not using bundler to run rake/rspec
> make sure we are always using bundler

- README.md
This stops the status badges looking blurry on hi-dpi displays.
> Updated README to use resolution independent badges

- lib/docker/util.rb
- spec/docker/container_spec.rb
- spec/docker/util_spec.rb
> ignore files based on dockerignore

- README.md
- lib/docker/container.rb
* Handle name key as hash while creating container
* Update README
> Improve name setting on creating container

- lib/docker/container.rb
- spec/docker/container_spec.rb
I needed it, and I saw the TODO.
@tlunter thoughts?
> Implement Container Stats Streaming

- README.md
A dokumentation how one could load Cert-Files from Variables like ENV Variables. All features provided by excon.
This should solve #343
> Added SSL Certs from Variable to Readme

- lib/docker.rb
- spec/docker_spec.rb
saw "version" errors popping up and got confused into thinking it had anything to do with versions not matching ... let's avoid that :)
@tlunter
> timeouts are not version errors

- lib/docker/container.rb
- spec/docker/container_spec.rb
Patch for https://github.com/swipely/docker-api/issues/352
> Add :format option to *top* method

- README.md
Related to #475 
@tlunter I couldn't think of a generic example, so I went with the one I knew. You are free to merge/modify.
> Add example for serveraddress to authenticate with different registry

- .travis.yml
- lib/docker/image.rb
- script/install_docker.sh
- spec/docker/container_spec.rb
- spec/docker/image_spec.rb
I have updated the tests to support version 1.12 an 1.13 
feel free to merge if useful
thanks for the library
cheers
> Add docker 1.13 and 1.12 to travis

- docker-api.gemspec
fixes https://github.com/swipely/docker-api/issues/491
> require at least excon 0.46.0

- .travis.yml
- lib/docker/container.rb
- lib/docker/image.rb
- lib/docker/network.rb
- lib/docker/volume.rb
- script/install_docker.sh
- spec/docker/container_spec.rb
- spec/docker/image_spec.rb
- spec/docker/network_spec.rb
- spec/docker/volume_spec.rb
- spec/spec_helper.rb
Hi.
The latest docker has new feature, `prune` and so I implemented it to your gem.
It helps us manage unused docker resources.
https://docs.docker.com/engine/reference/commandline/system_prune/
https://docs.docker.com/engine/api/v1.29/#operation/ContainerPrune
https://docs.docker.com/engine/api/v1.29/#operation/ImagePrune
https://docs.docker.com/engine/api/v1.29/#operation/NetworkPrune
https://docs.docker.com/engine/api/v1.29/#operation/VolumePrune
> Prune feature is implemented.

- docker-api.gemspec
- lib/docker.rb
- lib/docker/container.rb
- lib/docker/exec.rb
- lib/docker/image.rb
- lib/docker/network.rb
- lib/docker/util.rb
- lib/docker/volume.rb
- script/install_docker.sh
- spec/docker/event_spec.rb
- spec/docker/image_spec.rb
- spec/docker/util_spec.rb
- spec/docker_spec.rb
- spec/spec_helper.rb
> Removed JSON dependency, added MultiJson, fixed tests for Docker >= 0.12.5

- lib/docker/util.rb
This was missed during the MultiJson conversion
> Convert JSON to MultiJson in Docker::Util

- lib/docker/util.rb
- spec/docker/util_spec.rb
* Fixes #576 
This patch implements the logic described [in the Dockerfile reference for `.dockerignore`](https://docs.docker.com/engine/reference/builder/#dockerignore-file).
> Lines starting with `!` (exclamation mark) can be used to make exceptions to exclusions. The following is an example `.dockerignore` file that uses this mechanism:
> ```
> *.md
> !README.md
> ```
> All markdown files except `README.md` are excluded from the context.
> 
> The placement of ! exception rules influences the behavior: the last line of the `.dockerignore` that matches a particular file determines whether it is included or excluded. Consider the following example:
> 
> ```
> *.md
> !README*.md
> README-secret.md
> ```
> 
> No markdown files are included in the context except `README` files other …
> Fix docker context calculation re: .dockerignore
